### ISSUE TITLE
Replace California Prop 2 content with Jobs and Economy Canadian Content

### ISSUE THREAD

**Issue by ademidun** [atilatech/government-fyi#8]
- Replace the California Prop 2 with Canadian Housing Issue

- [x] Replace all urls that currently point to `prop-2` to point to `jobs-and-economy`
- [x] Replace monopoly hat image in props-2 to use monopoly cards image
- [x] Replace content for props 2 to use Jobs and Economy content from the [research google doc](https://docs.google.com/document/d/1r0bxUVZR_ernVrV0Jhwy7-1weESWNs4dJC-ZPKPyFwQ/edit)

Replace this image:
<img width="320" alt="Screen Shot 2019-10-13 at 6 29 21 PM" src="https://user-images.githubusercontent.com/9806858/66723511-f9760380-ede7-11e9-8674-b1196f25f756.png">

With this one instead:

<img width="307" alt="Screen Shot 2019-10-13 at 6 29 15 PM" src="https://user-images.githubusercontent.com/9806858/66723512-fed34e00-ede7-11e9-98ca-db8ed800adf0.png">

**Comment by mding5692** [comment]
@ademidun Yo add me to contributors

**Comment by mding5692** [comment]
This is done, u can review it if you want @ademidun
